[2019-05-01 14:12:20,291] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: Salted_Graph_Practice1.5.Sense_S3_Source 2019-05-01T18:11:13.044596+00:00 [queued]>
[2019-05-01 14:12:20,295] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: Salted_Graph_Practice1.5.Sense_S3_Source 2019-05-01T18:11:13.044596+00:00 [queued]>
[2019-05-01 14:12:20,295] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2019-05-01 14:12:20,295] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2019-05-01 14:12:20,295] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2019-05-01 14:12:20,303] {__init__.py:1374} INFO - Executing <Task(S3KeySensor): 5.Sense_S3_Source> on 2019-05-01T18:11:13.044596+00:00
[2019-05-01 14:12:20,303] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'Salted_Graph_Practice1', '5.Sense_S3_Source', '2019-05-01T18:11:13.044596+00:00', '--job_id', '341', '--raw', '-sd', 'DAGS_FOLDER/salted_graph.py', '--cfg_path', '/tmp/tmp831iqvh2']
[2019-05-01 14:12:20,574] {base_task_runner.py:101} INFO - Job 341: Subtask 5.Sense_S3_Source /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2019-05-01 14:12:20,574] {base_task_runner.py:101} INFO - Job 341: Subtask 5.Sense_S3_Source   FutureWarning,
[2019-05-01 14:12:20,749] {base_task_runner.py:101} INFO - Job 341: Subtask 5.Sense_S3_Source [2019-05-01 14:12:20,749] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-05-01 14:12:20,899] {base_task_runner.py:101} INFO - Job 341: Subtask 5.Sense_S3_Source [2019-05-01 14:12:20,898] {__init__.py:305} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/salted_graph.py
[2019-05-01 14:12:20,920] {base_task_runner.py:101} INFO - Job 341: Subtask 5.Sense_S3_Source [2019-05-01 14:12:20,920] {cli.py:517} INFO - Running <TaskInstance: Salted_Graph_Practice1.5.Sense_S3_Source 2019-05-01T18:11:13.044596+00:00 [running]> on host localhost.localdomain
[2019-05-01 14:12:20,960] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/yelp_subset_1.csv
[2019-05-01 14:12:20,976] {logging_mixin.py:95} INFO - [2019-05-01 14:12:20,976] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-05-01 14:12:21,285] {base_sensor_operator.py:124} INFO - Success criteria met. Exiting.
[2019-05-01 14:12:25,316] {logging_mixin.py:95} INFO - [2019-05-01 14:12:25,315] {jobs.py:2562} INFO - Task exited with return code 0
