[2019-04-29 13:06:14,473] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: pass_arg_print_name.detect 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 13:06:14,475] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: pass_arg_print_name.detect 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 13:06:14,475] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2019-04-29 13:06:14,475] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2019-04-29 13:06:14,475] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2019-04-29 13:06:14,483] {__init__.py:1374} INFO - Executing <Task(S3KeySensor): detect> on 2019-04-28T00:00:00+00:00
[2019-04-29 13:06:14,483] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'pass_arg_print_name', 'detect', '2019-04-28T00:00:00+00:00', '--job_id', '160', '--raw', '-sd', 'DAGS_FOLDER/arg_passing.py', '--cfg_path', '/tmp/tmp4bcyv0p0']
[2019-04-29 13:06:14,752] {base_task_runner.py:101} INFO - Job 160: Subtask detect /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2019-04-29 13:06:14,752] {base_task_runner.py:101} INFO - Job 160: Subtask detect   FutureWarning,
[2019-04-29 13:06:14,906] {base_task_runner.py:101} INFO - Job 160: Subtask detect [2019-04-29 13:06:14,906] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-29 13:06:15,045] {base_task_runner.py:101} INFO - Job 160: Subtask detect [2019-04-29 13:06:15,045] {__init__.py:305} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/arg_passing.py
[2019-04-29 13:06:15,182] {base_task_runner.py:101} INFO - Job 160: Subtask detect [2019-04-29 13:06:15,182] {cli.py:517} INFO - Running <TaskInstance: pass_arg_print_name.detect 2019-04-28T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-04-29 13:06:15,240] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/yelp_subset_1.csv
[2019-04-29 13:06:15,256] {logging_mixin.py:95} INFO - [2019-04-29 13:06:15,256] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 13:06:15,573] {base_sensor_operator.py:124} INFO - Success criteria met. Exiting.
[2019-04-29 13:06:19,483] {logging_mixin.py:95} INFO - [2019-04-29 13:06:19,483] {jobs.py:2562} INFO - Task exited with return code 0
