[2019-04-29 11:33:43,439] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: do_more_in_python2.detect 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 11:33:43,441] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: do_more_in_python2.detect 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 11:33:43,441] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2019-04-29 11:33:43,441] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2019-04-29 11:33:43,441] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2019-04-29 11:33:43,450] {__init__.py:1374} INFO - Executing <Task(S3KeySensor): detect> on 2019-04-28T00:00:00+00:00
[2019-04-29 11:33:43,450] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'do_more_in_python2', 'detect', '2019-04-28T00:00:00+00:00', '--job_id', '140', '--raw', '-sd', 'DAGS_FOLDER/python_operator_challenge.py', '--cfg_path', '/tmp/tmp5istwsx1']
[2019-04-29 11:33:43,725] {base_task_runner.py:101} INFO - Job 140: Subtask detect /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2019-04-29 11:33:43,726] {base_task_runner.py:101} INFO - Job 140: Subtask detect   FutureWarning,
[2019-04-29 11:33:43,881] {base_task_runner.py:101} INFO - Job 140: Subtask detect [2019-04-29 11:33:43,881] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-29 11:33:44,021] {base_task_runner.py:101} INFO - Job 140: Subtask detect [2019-04-29 11:33:44,021] {__init__.py:305} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/python_operator_challenge.py
[2019-04-29 11:33:44,159] {base_task_runner.py:101} INFO - Job 140: Subtask detect [2019-04-29 11:33:44,158] {cli.py:517} INFO - Running <TaskInstance: do_more_in_python2.detect 2019-04-28T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-04-29 11:33:44,216] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/yelp_subset_1.csv
[2019-04-29 11:33:44,233] {logging_mixin.py:95} INFO - [2019-04-29 11:33:44,232] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 11:33:44,597] {base_sensor_operator.py:124} INFO - Success criteria met. Exiting.
[2019-04-29 11:33:48,456] {logging_mixin.py:95} INFO - [2019-04-29 11:33:48,456] {jobs.py:2562} INFO - Task exited with return code 0
