[2019-04-30 13:30:09,806] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: Salted_Graph_Practice1.Sense_S3_Source_Data 2019-04-30T17:30:07.704232+00:00 [queued]>
[2019-04-30 13:30:09,808] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: Salted_Graph_Practice1.Sense_S3_Source_Data 2019-04-30T17:30:07.704232+00:00 [queued]>
[2019-04-30 13:30:09,808] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2019-04-30 13:30:09,808] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2019-04-30 13:30:09,808] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2019-04-30 13:30:09,817] {__init__.py:1374} INFO - Executing <Task(S3KeySensor): Sense_S3_Source_Data> on 2019-04-30T17:30:07.704232+00:00
[2019-04-30 13:30:09,817] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'Salted_Graph_Practice1', 'Sense_S3_Source_Data', '2019-04-30T17:30:07.704232+00:00', '--job_id', '192', '--raw', '-sd', 'DAGS_FOLDER/salted_graph.py', '--cfg_path', '/tmp/tmpi5e23q_d']
[2019-04-30 13:30:10,077] {base_task_runner.py:101} INFO - Job 192: Subtask Sense_S3_Source_Data /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2019-04-30 13:30:10,077] {base_task_runner.py:101} INFO - Job 192: Subtask Sense_S3_Source_Data   FutureWarning,
[2019-04-30 13:30:10,222] {base_task_runner.py:101} INFO - Job 192: Subtask Sense_S3_Source_Data [2019-04-30 13:30:10,222] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-30 13:30:10,357] {base_task_runner.py:101} INFO - Job 192: Subtask Sense_S3_Source_Data [2019-04-30 13:30:10,357] {__init__.py:305} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/salted_graph.py
[2019-04-30 13:30:10,496] {base_task_runner.py:101} INFO - Job 192: Subtask Sense_S3_Source_Data [2019-04-30 13:30:10,496] {cli.py:517} INFO - Running <TaskInstance: Salted_Graph_Practice1.Sense_S3_Source_Data 2019-04-30T17:30:07.704232+00:00 [running]> on host localhost.localdomain
[2019-04-30 13:30:10,553] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/yelp_subset_1.csv
[2019-04-30 13:30:10,569] {logging_mixin.py:95} INFO - [2019-04-30 13:30:10,569] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-30 13:30:10,849] {base_sensor_operator.py:124} INFO - Success criteria met. Exiting.
[2019-04-30 13:30:14,815] {logging_mixin.py:95} INFO - [2019-04-30 13:30:14,815] {jobs.py:2562} INFO - Task exited with return code 0
