[2019-04-30 15:23:51,937] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: Salted_Graph_Practice1.Sense_S3_Source_Data 2019-04-30T19:23:50.687305+00:00 [queued]>
[2019-04-30 15:23:51,939] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: Salted_Graph_Practice1.Sense_S3_Source_Data 2019-04-30T19:23:50.687305+00:00 [queued]>
[2019-04-30 15:23:51,939] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2019-04-30 15:23:51,939] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2019-04-30 15:23:51,939] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2019-04-30 15:23:51,948] {__init__.py:1374} INFO - Executing <Task(S3KeySensor): Sense_S3_Source_Data> on 2019-04-30T19:23:50.687305+00:00
[2019-04-30 15:23:51,949] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'Salted_Graph_Practice1', 'Sense_S3_Source_Data', '2019-04-30T19:23:50.687305+00:00', '--job_id', '216', '--raw', '-sd', 'DAGS_FOLDER/salted_graph.py', '--cfg_path', '/tmp/tmp7boo3v_t']
[2019-04-30 15:23:52,235] {base_task_runner.py:101} INFO - Job 216: Subtask Sense_S3_Source_Data /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2019-04-30 15:23:52,235] {base_task_runner.py:101} INFO - Job 216: Subtask Sense_S3_Source_Data   FutureWarning,
[2019-04-30 15:23:52,385] {base_task_runner.py:101} INFO - Job 216: Subtask Sense_S3_Source_Data [2019-04-30 15:23:52,385] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-30 15:23:52,523] {base_task_runner.py:101} INFO - Job 216: Subtask Sense_S3_Source_Data [2019-04-30 15:23:52,523] {__init__.py:305} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/salted_graph.py
[2019-04-30 15:23:52,544] {base_task_runner.py:101} INFO - Job 216: Subtask Sense_S3_Source_Data [2019-04-30 15:23:52,544] {cli.py:517} INFO - Running <TaskInstance: Salted_Graph_Practice1.Sense_S3_Source_Data 2019-04-30T19:23:50.687305+00:00 [running]> on host localhost.localdomain
[2019-04-30 15:23:52,580] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/yelp_subset_1.csv
[2019-04-30 15:23:52,596] {logging_mixin.py:95} INFO - [2019-04-30 15:23:52,596] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-30 15:23:52,952] {base_sensor_operator.py:124} INFO - Success criteria met. Exiting.
[2019-04-30 15:23:56,959] {logging_mixin.py:95} INFO - [2019-04-30 15:23:56,959] {jobs.py:2562} INFO - Task exited with return code 0
