[2019-04-29 07:36:25,796] {models.py:1359} INFO - Dependencies all met for <TaskInstance: s3_yelp_sensor.s3_file_test 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 07:36:25,797] {models.py:1359} INFO - Dependencies all met for <TaskInstance: s3_yelp_sensor.s3_file_test 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 07:36:25,797] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2019-04-29 07:36:25,806] {models.py:1593} INFO - Executing <Task(S3KeySensor): s3_file_test> on 2019-04-28T00:00:00+00:00
[2019-04-29 07:36:25,806] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run s3_yelp_sensor s3_file_test 2019-04-28T00:00:00+00:00 --job_id 99 --raw -sd DAGS_FOLDER/AWS_Challenge.py --cfg_path /tmp/tmp228f5omv']
[2019-04-29 07:36:26,249] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test [2019-04-29 07:36:26,249] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-29 07:36:26,400] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test [2019-04-29 07:36:26,399] {models.py:273} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/AWS_Challenge.py
[2019-04-29 07:36:26,434] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test [2019-04-29 07:36:26,434] {cli.py:520} INFO - Running <TaskInstance: s3_yelp_sensor.s3_file_test 2019-04-28T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-04-29 07:36:26,475] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:26,491] {logging_mixin.py:95} INFO - [2019-04-29 07:36:26,490] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:26,819] {logging_mixin.py:95} INFO - [2019-04-29 07:36:26,818] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:26,821] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:26,859] {logging_mixin.py:95} INFO - [2019-04-29 07:36:26,859] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:27,190] {logging_mixin.py:95} INFO - [2019-04-29 07:36:27,189] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:27,192] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:27,229] {logging_mixin.py:95} INFO - [2019-04-29 07:36:27,229] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:27,607] {logging_mixin.py:95} INFO - [2019-04-29 07:36:27,607] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:27,610] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:27,645] {logging_mixin.py:95} INFO - [2019-04-29 07:36:27,645] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:27,957] {logging_mixin.py:95} INFO - [2019-04-29 07:36:27,957] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:27,960] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:27,998] {logging_mixin.py:95} INFO - [2019-04-29 07:36:27,997] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:28,555] {logging_mixin.py:95} INFO - [2019-04-29 07:36:28,555] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:28,558] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:28,592] {logging_mixin.py:95} INFO - [2019-04-29 07:36:28,592] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:28,982] {logging_mixin.py:95} INFO - [2019-04-29 07:36:28,982] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:28,984] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:29,022] {logging_mixin.py:95} INFO - [2019-04-29 07:36:29,022] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:29,412] {logging_mixin.py:95} INFO - [2019-04-29 07:36:29,411] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:29,415] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:29,453] {logging_mixin.py:95} INFO - [2019-04-29 07:36:29,453] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:29,892] {logging_mixin.py:95} INFO - [2019-04-29 07:36:29,892] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:29,896] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:29,932] {logging_mixin.py:95} INFO - [2019-04-29 07:36:29,932] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:30,320] {logging_mixin.py:95} INFO - [2019-04-29 07:36:30,320] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:30,323] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:30,361] {logging_mixin.py:95} INFO - [2019-04-29 07:36:30,360] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:30,701] {logging_mixin.py:95} INFO - [2019-04-29 07:36:30,701] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:30,702] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:30,713] {logging_mixin.py:95} INFO - [2019-04-29 07:36:30,713] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:30,989] {logging_mixin.py:95} INFO - [2019-04-29 07:36:30,989] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:30,992] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:31,030] {logging_mixin.py:95} INFO - [2019-04-29 07:36:31,030] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:31,663] {logging_mixin.py:95} INFO - [2019-04-29 07:36:31,662] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:31,665] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:31,699] {logging_mixin.py:95} INFO - [2019-04-29 07:36:31,699] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:32,003] {logging_mixin.py:95} INFO - [2019-04-29 07:36:32,003] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:32,006] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:32,043] {logging_mixin.py:95} INFO - [2019-04-29 07:36:32,043] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:32,341] {logging_mixin.py:95} INFO - [2019-04-29 07:36:32,341] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:32,344] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:32,381] {logging_mixin.py:95} INFO - [2019-04-29 07:36:32,381] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:32,677] {logging_mixin.py:95} INFO - [2019-04-29 07:36:32,677] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:32,677] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:32,689] {logging_mixin.py:95} INFO - [2019-04-29 07:36:32,689] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:33,043] {logging_mixin.py:95} INFO - [2019-04-29 07:36:33,043] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:33,046] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:33,083] {logging_mixin.py:95} INFO - [2019-04-29 07:36:33,083] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:33,379] {logging_mixin.py:95} INFO - [2019-04-29 07:36:33,379] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:33,382] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:33,420] {logging_mixin.py:95} INFO - [2019-04-29 07:36:33,420] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:33,817] {logging_mixin.py:95} INFO - [2019-04-29 07:36:33,817] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:33,820] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:33,855] {logging_mixin.py:95} INFO - [2019-04-29 07:36:33,855] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:34,213] {logging_mixin.py:95} INFO - [2019-04-29 07:36:34,213] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:34,216] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:34,252] {logging_mixin.py:95} INFO - [2019-04-29 07:36:34,252] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:34,547] {logging_mixin.py:95} INFO - [2019-04-29 07:36:34,547] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:34,550] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:34,588] {logging_mixin.py:95} INFO - [2019-04-29 07:36:34,588] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:34,871] {logging_mixin.py:95} INFO - [2019-04-29 07:36:34,871] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:34,874] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:34,911] {logging_mixin.py:95} INFO - [2019-04-29 07:36:34,910] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:35,192] {logging_mixin.py:95} INFO - [2019-04-29 07:36:35,192] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:35,196] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:35,232] {logging_mixin.py:95} INFO - [2019-04-29 07:36:35,232] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:35,514] {logging_mixin.py:95} INFO - [2019-04-29 07:36:35,514] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:35,517] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:35,555] {logging_mixin.py:95} INFO - [2019-04-29 07:36:35,555] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:35,956] {logging_mixin.py:95} INFO - [2019-04-29 07:36:35,956] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:35,959] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:35,996] {logging_mixin.py:95} INFO - [2019-04-29 07:36:35,996] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:36,366] {logging_mixin.py:95} INFO - [2019-04-29 07:36:36,365] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:36,366] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/
[2019-04-29 07:36:36,377] {logging_mixin.py:95} INFO - [2019-04-29 07:36:36,377] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 07:36:36,640] {logging_mixin.py:95} INFO - [2019-04-29 07:36:36,640] {S3_hook.py:201} INFO - Not Found
[2019-04-29 07:36:36,643] {models.py:1788} ERROR - Snap. Time is OUT.
Traceback (most recent call last):
  File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/models.py", line 1657, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/sensors/base_sensor_operator.py", line 106, in execute
    raise AirflowSensorTimeout('Snap. Time is OUT.')
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT.
[2019-04-29 07:36:36,644] {models.py:1811} INFO - Marking task as UP_FOR_RETRY
[2019-04-29 07:36:36,654] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test /home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/utils/helpers.py:356: DeprecationWarning: Importing 'BashOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2019-04-29 07:36:36,654] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test   DeprecationWarning)
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test Traceback (most recent call last):
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/bin/airflow", line 32, in <module>
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test     args.func(args)
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test     return f(*args, **kwargs)
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/bin/cli.py", line 526, in run
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test     _run(args, dag, ti)
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/bin/cli.py", line 445, in _run
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test     pool=args.pool,
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-04-29 07:36:36,655] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test     return func(*args, **kwargs)
[2019-04-29 07:36:36,656] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/models.py", line 1657, in _run_raw_task
[2019-04-29 07:36:36,656] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test     result = task_copy.execute(context=context)
[2019-04-29 07:36:36,656] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/sensors/base_sensor_operator.py", line 106, in execute
[2019-04-29 07:36:36,656] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test     raise AirflowSensorTimeout('Snap. Time is OUT.')
[2019-04-29 07:36:36,656] {base_task_runner.py:101} INFO - Job 99: Subtask s3_file_test airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT.
[2019-04-29 07:36:40,827] {logging_mixin.py:95} INFO - [2019-04-29 07:36:40,827] {jobs.py:2527} INFO - Task exited with return code 1
