[2019-04-29 07:09:31,895] {models.py:1359} INFO - Dependencies all met for <TaskInstance: s3_file_sensor.s3_file_test 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 07:09:31,896] {models.py:1359} INFO - Dependencies all met for <TaskInstance: s3_file_sensor.s3_file_test 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 07:09:31,896] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 2 of 2
--------------------------------------------------------------------------------

[2019-04-29 07:09:31,905] {models.py:1593} INFO - Executing <Task(S3KeySensor): s3_file_test> on 2019-04-28T00:00:00+00:00
[2019-04-29 07:09:31,905] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run s3_file_sensor s3_file_test 2019-04-28T00:00:00+00:00 --job_id 91 --raw -sd DAGS_FOLDER/AWS_Challenge.py --cfg_path /tmp/tmp8m9ykk0j']
[2019-04-29 07:09:32,273] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test [2019-04-29 07:09:32,272] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-29 07:09:32,456] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test [2019-04-29 07:09:32,455] {models.py:273} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/AWS_Challenge.py
[2019-04-29 07:09:32,477] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test [2019-04-29 07:09:32,477] {cli.py:520} INFO - Running <TaskInstance: s3_file_sensor.s3_file_test 2019-04-28T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-04-29 07:09:32,484] {models.py:1788} ERROR - No module named 'botocore'
Traceback (most recent call last):
  File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/models.py", line 1657, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/sensors/base_sensor_operator.py", line 97, in execute
    while not self.poke(context):
  File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/sensors/s3_key_sensor.py", line 85, in poke
    from airflow.hooks.S3_hook import S3Hook
  File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/hooks/S3_hook.py", line 19, in <module>
    from botocore.exceptions import ClientError
ImportError: No module named 'botocore'
[2019-04-29 07:09:32,485] {models.py:1817} INFO - All retries failed; marking task as FAILED
[2019-04-29 07:09:32,495] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test /home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/utils/helpers.py:356: DeprecationWarning: Importing 'BashOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2019-04-29 07:09:32,495] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test   DeprecationWarning)
[2019-04-29 07:09:32,499] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test Traceback (most recent call last):
[2019-04-29 07:09:32,499] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/bin/airflow", line 32, in <module>
[2019-04-29 07:09:32,499] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test     args.func(args)
[2019-04-29 07:09:32,499] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-04-29 07:09:32,499] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test     return f(*args, **kwargs)
[2019-04-29 07:09:32,499] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/bin/cli.py", line 526, in run
[2019-04-29 07:09:32,499] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test     _run(args, dag, ti)
[2019-04-29 07:09:32,499] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/bin/cli.py", line 445, in _run
[2019-04-29 07:09:32,499] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test     pool=args.pool,
[2019-04-29 07:09:32,499] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-04-29 07:09:32,500] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test     return func(*args, **kwargs)
[2019-04-29 07:09:32,500] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/models.py", line 1657, in _run_raw_task
[2019-04-29 07:09:32,500] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test     result = task_copy.execute(context=context)
[2019-04-29 07:09:32,500] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/sensors/base_sensor_operator.py", line 97, in execute
[2019-04-29 07:09:32,500] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test     while not self.poke(context):
[2019-04-29 07:09:32,500] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/sensors/s3_key_sensor.py", line 85, in poke
[2019-04-29 07:09:32,500] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test     from airflow.hooks.S3_hook import S3Hook
[2019-04-29 07:09:32,500] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test   File "/home/mjcarleb/anaconda3/envs/airflow/lib/python3.5/site-packages/airflow/hooks/S3_hook.py", line 19, in <module>
[2019-04-29 07:09:32,500] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test     from botocore.exceptions import ClientError
[2019-04-29 07:09:32,500] {base_task_runner.py:101} INFO - Job 91: Subtask s3_file_test ImportError: No module named 'botocore'
[2019-04-29 07:09:36,911] {logging_mixin.py:95} INFO - [2019-04-29 07:09:36,911] {jobs.py:2527} INFO - Task exited with return code 1
