[2019-04-30 17:22:08,921] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: Mixed_Failing_Demo.6a_change_dir1 2019-04-30T21:21:31.051930+00:00 [queued]>
[2019-04-30 17:22:08,925] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: Mixed_Failing_Demo.6a_change_dir1 2019-04-30T21:21:31.051930+00:00 [queued]>
[2019-04-30 17:22:08,925] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2019-04-30 17:22:08,925] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2019-04-30 17:22:08,925] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2019-04-30 17:22:08,933] {__init__.py:1374} INFO - Executing <Task(BashOperator): 6a_change_dir1> on 2019-04-30T21:21:31.051930+00:00
[2019-04-30 17:22:08,933] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'Mixed_Failing_Demo', '6a_change_dir1', '2019-04-30T21:21:31.051930+00:00', '--job_id', '241', '--raw', '-sd', 'DAGS_FOLDER/mixed_failing.py', '--cfg_path', '/tmp/tmpaed6e9zd']
[2019-04-30 17:22:09,196] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1 /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2019-04-30 17:22:09,196] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1   FutureWarning,
[2019-04-30 17:22:09,353] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1 [2019-04-30 17:22:09,353] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-30 17:22:09,502] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1 [2019-04-30 17:22:09,501] {__init__.py:305} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/mixed_failing.py
[2019-04-30 17:22:09,522] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1 [2019-04-30 17:22:09,522] {cli.py:517} INFO - Running <TaskInstance: Mixed_Failing_Demo.6a_change_dir1 2019-04-30T21:21:31.051930+00:00 [running]> on host localhost.localdomain
[2019-04-30 17:22:09,529] {bash_operator.py:81} INFO - Tmp dir root location: 
 /tmp
[2019-04-30 17:22:09,529] {bash_operator.py:90} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=Mixed_Failing_Demo
AIRFLOW_CTX_TASK_ID=6a_change_dir1
AIRFLOW_CTX_EXECUTION_DATE=2019-04-30T21:21:31.051930+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2019-04-30T21:21:31.051930+00:00
[2019-04-30 17:22:09,529] {bash_operator.py:104} INFO - Temporary script location: /tmp/airflowtmpjnslo0yu/6a_change_dir1rj4_2y45
[2019-04-30 17:22:09,529] {bash_operator.py:114} INFO - Running command: cd dfsjkl$AIRFLOW_HOME
[2019-04-30 17:22:09,533] {bash_operator.py:123} INFO - Output:
[2019-04-30 17:22:09,534] {bash_operator.py:127} INFO - /tmp/airflowtmpjnslo0yu/6a_change_dir1rj4_2y45: line 1: cd: dfsjkl/home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb: No such file or directory
[2019-04-30 17:22:09,534] {bash_operator.py:131} INFO - Command exited with return code 1
[2019-04-30 17:22:09,538] {__init__.py:1580} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 135, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2019-04-30 17:22:09,539] {__init__.py:1611} INFO - Marking task as FAILED.
[2019-04-30 17:22:09,549] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1 Traceback (most recent call last):
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1   File "/home/mjcarleb/anaconda3/envs/airflow4/bin/airflow", line 32, in <module>
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1     args.func(args)
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1     return f(*args, **kwargs)
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1     _run(args, dag, ti)
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/bin/cli.py", line 442, in _run
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1     pool=args.pool,
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1     return func(*args, **kwargs)
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1     result = task_copy.execute(context=context)
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 135, in execute
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1     raise AirflowException("Bash command failed")
[2019-04-30 17:22:09,550] {base_task_runner.py:101} INFO - Job 241: Subtask 6a_change_dir1 airflow.exceptions.AirflowException: Bash command failed
[2019-04-30 17:22:13,933] {logging_mixin.py:95} INFO - [2019-04-30 17:22:13,933] {jobs.py:2562} INFO - Task exited with return code 1
