[2019-04-29 11:39:21,729] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: read_csv_into_dataframe.detect 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 11:39:21,732] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: read_csv_into_dataframe.detect 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 11:39:21,732] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2019-04-29 11:39:21,732] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2019-04-29 11:39:21,732] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2019-04-29 11:39:21,741] {__init__.py:1374} INFO - Executing <Task(S3KeySensor): detect> on 2019-04-28T00:00:00+00:00
[2019-04-29 11:39:21,741] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'read_csv_into_dataframe', 'detect', '2019-04-28T00:00:00+00:00', '--job_id', '145', '--raw', '-sd', 'DAGS_FOLDER/python_operator_challenge.py', '--cfg_path', '/tmp/tmpfeymjp_z']
[2019-04-29 11:39:22,006] {base_task_runner.py:101} INFO - Job 145: Subtask detect /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2019-04-29 11:39:22,006] {base_task_runner.py:101} INFO - Job 145: Subtask detect   FutureWarning,
[2019-04-29 11:39:22,151] {base_task_runner.py:101} INFO - Job 145: Subtask detect [2019-04-29 11:39:22,151] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-29 11:39:22,286] {base_task_runner.py:101} INFO - Job 145: Subtask detect [2019-04-29 11:39:22,286] {__init__.py:305} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/python_operator_challenge.py
[2019-04-29 11:39:22,427] {base_task_runner.py:101} INFO - Job 145: Subtask detect [2019-04-29 11:39:22,427] {cli.py:517} INFO - Running <TaskInstance: read_csv_into_dataframe.detect 2019-04-28T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-04-29 11:39:22,484] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/yelp_subset_1.csv
[2019-04-29 11:39:22,500] {logging_mixin.py:95} INFO - [2019-04-29 11:39:22,499] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 11:39:22,839] {base_sensor_operator.py:124} INFO - Success criteria met. Exiting.
[2019-04-29 11:39:26,744] {logging_mixin.py:95} INFO - [2019-04-29 11:39:26,743] {jobs.py:2562} INFO - Task exited with return code 0
